import React, { useState } from "react";
import "./styles.css";

export default function App() {
  const [theme, setTheme] = useState("light");
  const [mode, setMode] = useState("academic");
  const [transcript, setTranscript] = useState("");
  const [summary, setSummary] = useState("");
  const [tasks, setTasks] = useState("");
  const [deadlines, setDeadlines] = useState("");
  const [highlights, setHighlights] = useState("");
  const [notes, setNotes] = useState("");

  const toggleTheme = () => {
    const newTheme = theme === "light" ? "dark" : "light";
    setTheme(newTheme);
    document.body.className = newTheme;
  };

  const handleSummary = () => {
    const content =
      mode === "academic"
        ? "Academic Summary: The lecture covered key concepts and findings relevant to the course."
        : "Business Summary: The meeting outlined goals, updates, and next steps.";
    setSummary(content);
  };

  const handleTasks = () => {
    const list =
      mode === "academic"
        ? "- Submit assignment\n- Revise lecture notes"
        : "- Email client\n- Schedule next sync";
    setTasks(list);
  };

  const handleDeadlines = () => {
    const deadline =
      mode === "academic"
        ? "Project deadline: Friday"
        : "Client proposal due: Friday";
    setDeadlines(deadline);
  };

  const handleHighlights = () => {
    const point =
      mode === "academic"
        ? "Highlighted Topic: Generative AI in education"
        : "Key Decision: Move forward with beta release";
    setHighlights(point);
  };

  const handleExport = () => {
    const content = `
AutoScribe.AI Export – ${mode.toUpperCase()} MODE

Summary:
${summary}

Tasks:
${tasks}

Deadlines:
${deadlines}

Highlights:
${highlights}

Notes:
${notes}

— Generated by AutoScribe.AI
Aman Kumar | BTech ECE CORE
SRM Institute of Science and Technology, Kattankulathur, Chennai
Email: iamankr886@gmail.com
GitHub: https://github.com/YukiCodepth
LinkedIn: https://www.linkedin.com/in/aman-kumar-429086299/
    `.trim();

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.download = "AutoScribe_Export.txt";
    link.href = url;
    link.click();
  };

  return (
    <div className="app">
      <h1 className="logo-title">AutoScribe.AI</h1>

      <div className="top-bar">
        <button onClick={toggleTheme}>Toggle {theme === "light" ? "Dark" : "Light"} Mode</button>
        <div className="mode-toggle">
          <label>
            <input
              type="radio"
              name="mode"
              value="academic"
              checked={mode === "academic"}
              onChange={() => setMode("academic")}
            />
            Academic
          </label>
          <label>
            <input
              type="radio"
              name="mode"
              value="business"
              checked={mode === "business"}
              onChange={() => setMode("business")}
            />
            Business
          </label>
        </div>
      </div>

      <textarea
        value={transcript}
        onChange={(e) => setTranscript(e.target.value)}
        placeholder="Paste your transcript here..."
        rows={6}
      />

      <div className="buttons">
        <button onClick={handleSummary}>Generate Summary</button>
        <button onClick={handleTasks}>Extract Tasks</button>
        <button onClick={handleDeadlines}>Find Deadlines</button>
        <button onClick={handleHighlights}>Get Highlights</button>
        <button onClick={handleExport}>Export Notes</button>
      </div>

      <div className="output-section">
        <h3>Summary</h3>
        <p>{summary}</p>

        <h3>Tasks</h3>
        <p>{tasks}</p>

        <h3>Deadlines</h3>
        <p>{deadlines}</p>

        <h3>Highlights</h3>
        <p>{highlights}</p>

        <h3>Personal Notes</h3>
        <textarea
          value={notes}
          onChange={(e) => setNotes(e.target.value)}
          placeholder="Add your notes..."
          rows={3}
        />
      </div>

      <footer>
        <hr />
        <p><strong>Aman Kumar</strong> – BTech ECE CORE</p>
        <p>SRM Institute of Science and Technology, Kattankulathur, Chennai</p>
        <p>
          <a href="mailto:iamankr886@gmail.com">iamankr886@gmail.com</a> |
          <a href="https://github.com/YukiCodepth" target="_blank" rel="noreferrer"> GitHub</a> |
          <a href="https://www.linkedin.com/in/aman-kumar-429086299/" target="_blank" rel="noreferrer"> LinkedIn</a>
        </p>
      </footer>
    </div>
  );
}
